export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";

export const CHECK_SESSION_STATUS = "CHECK_SESSION_STATUS";