export const LOAD_BOARD_REQUEST = "LOAD_BOARD_REQUEST"
export const LOAD_BOARD_SUCCESS = "LOAD_BOARD_SUCCESS"
export const LOAD_BOARD_FAILURE = "LOAD_BOARD_FAILURE"

export const LOAD_BOARD_BY_STAGE_REQUEST = "LOAD_BOARD_BY_STAGE_REQUEST"
export const LOAD_BOARD_BY_STAGE_SUCCESS = "LOAD_BOARD_BY_STAGE_SUCCESS"
export const LOAD_BOARD_BY_STAGE_FAILURE = "LOAD_BOARD_BY_STAGE_FAILURE"

export const CREATE_COLUMN_REQUEST = "CREATE_COLUMN_REQUEST"
export const CREATE_COLUMN_SUCCESS = "CREATE_COLUMN_SUCCESS"
export const CREATE_COLUMN_FAILURE = "CREATE_COLUMN_FAILURE"

export const UPDATE_COLUMN_REQUEST = "UPDATE_COLUMN_REQUEST"
export const UPDATE_COLUMN_SUCCESS = "UPDATE_COLUMN_SUCCESS"
export const UPDATE_COLUMN_FAILURE = "UPDATE_COLUMN_FAILURE"

export const DELETE_COLUMN_REQUEST = "DELETE_COLUMN_REQUEST"
export const DELETE_COLUMN_SUCCESS = "DELETE_COLUMN_SUCCESS"
export const DELETE_COLUMN_FAILURE = "DELETE_COLUMN_FAILURE"

export const CREATE_CARD_REQUEST = "CREATE_CARD_REQUEST"
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE"

export const UPDATE_CARD_REQUEST = "UPDATE_CARD_REQUEST"
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS"
export const UPDATE_CARD_FAILURE = "UPDATE_CARD_FAILURE"

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST"
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS"
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE"

export const MOVE_CARD_REQUEST = "MOVE_CARD_REQUEST"
export const MOVE_CARD_SUCCESS = "MOVE_CARD_SUCCESS"
export const MOVE_CARD_FAILURE = "MOVE_CARD_FAILURE"